name: Modify Crystal Shape
description: Change dimensions or color of the crystal
title: "Update Crystal: [Make Selection]"
labels: ["automated-update"]
body:
  - type: markdown
    attributes:
      value: |
        Use the form below to update the 3D model. The bot will process this automatically.

  - type: dropdown
    id: operation
    attributes:
      label: What do you want to change?
      options:
        - "Change Color"
        - "Update Height"
        - "Update Radius"
    validations:
      required: true

  - type: input
    id: value
    attributes:
      label: New Value
      description: "For Color: Enter a Hex code (e.g. #FF5733). For Dimensions: Enter a number (e.g. 20)."
      placeholder: "#FF5733 or 20"
    validations:
      required: true
